* consortium

A consortium is an association of two or more
individuals, companies, organizations, or governments
with the objective of participating in a common activity or pooling their resources
for achieving a common goal.

Consortium is a Latin word meaning
"partnership", "association", or "society",
and derives from consors ("shared in property"),
itself from con- ("together") and sors ("fate").

Consortium system is a coordination layer for interprocess communication of Common Lisp images.
Each image (exempli gratia: StumpWM, Nyxt, Lem, Autolith etc.)
independently registers itself with consortium
creating a mesh of cooperating Lisp processes that can evaluate code
in each other and share symbols — a lightweight Lisp machine on the network without rewriting the world.

WIP
This is just at the stage of layout and rough in.

TODO Server functions need attention next.
My clanker knew swank, so I didnt fight it during design, but I am replacing swank with micros.

TODO eliminate the configuration line. declaring the dependency in asdf should be sufficient to register.
 maybe a macro in an init function under eval-when control.


* eg configuration

FILE ~/.stumpwmrc
#+begin_src lisp
  (asdf:load-system :metarepl.image.consortium)
  (consortium:register-source :stumpwm)
#+end_src

FILE ~/.nyxtrc
#+begin_src lisp
  (asdf:load-system :metarepl.image.consortium)
  (consortium:register-source :stumpwm)
#+end_src

Then from any node:
#+begin_src lisp
  (consortium:nodes)

  (consortium:eval-at "nyxt" '(nyxt:current-url))

  (consortium:sync-all)
#+end_src

* eg configuration minimal

FILE ~/.stumpwmrc
#+begin_src lisp
  (asdf:load-system :micros)
  (asdf:load-system :metarepl.image.consortium)
  (consortium/minimal:register "stumpwm" 40001)
#+end_src

FILE ~/.nyxtrc
#+begin_src lisp
  (asdf:load-system :micros)
  (asdf:load-system :metarepl.image.consortium)
  (consortium/minimal:register "nyxt" 40002)
#+end_src

From either image:
#+begin_src lisp
(consortium/minimal:nodes)
;; => ((:NAME "stumpwm" :PORT 40001) (:NAME "nyxt" :PORT 40002))

(consortium/minimal:eval-at "nyxt" '(+ 1 1))
;; => 2

(consortium/minimal:eval-at "stumpwm" '(stumpwm:current-window))
#+end_src
